- .github/pull-request-template.md
**Changes:**
- add pull request template
> docs: add pr template

- config/manager/kustomization.yaml
- deploy/vance-1.0.0.yaml
**Changes:**
- update deploy YAML file
> docs: update vance yaml file

- .gitignore
**Changes:**
- update gitignore
> feat: update gitignore

- connectors/sink-http/README.md
- connectors/sink-http/pom.xml
- connectors/sink-http/src/main/java/com/linkall/sink/http/Entrance.java
- connectors/sink-http/src/main/java/com/linkall/sink/http/HttpSink.java
- connectors/sink-http/src/main/resources/config.json
**Changes:**
- add a new connector: sink-http
> feat: add sink-http

- connectors/sink-feishu-bot/README.md
- connectors/sink-feishu-bot/pom.xml
- connectors/sink-feishu-bot/src/main/java/com/linkall/sink/feishubot/Entrance.java
- connectors/sink-feishu-bot/src/main/java/com/linkall/sink/feishubot/FeishuBotSink.java
- connectors/sink-feishu-bot/src/main/resources/config.json
**Changes:**
- add a new connector sink-feishu-bot
> feat: add a new connector sink-feishu-bot

- connectors/source-http/README.md
**Changes:**
- docs: update http source README
> docs: update http source README

- connectors/README.md
**Changes:**
- update connectors README.md
> docs: update connectors README.md

- connectors/sink-http/README.md
**Changes:**
- update README.md of HTTP Sink
> docs: update README.md of HTTP Sink

- Makefile
- connectors/sink-feishu/README.md
- connectors/sink-feishu/go.mod
- connectors/sink-feishu/go.sum
- connectors/sink-feishu/internal/bot.go
- connectors/sink-feishu/internal/server.go
- connectors/sink-feishu/sink-feishu.yml
**Changes:**
- add log
- modify sink-feishu.yml
> feat: add error response handler

- connectors/sink-feishu/internal/server.go
**Changes:**
- change vanceServiceNameAttribute shorter
> fix: change vanceServiceNameAttribute shorter

- connectors/sink-feishu/README.md
- connectors/sink-feishu/internal/bot.go
- connectors/sink-feishu/internal/server.go
- connectors/sink-feishu/sink-feishu.yml
**Changes:**
- support multiple chatgroups.
- support message type of post, image, share_chat, and interactive.
Close #99
> feat: Feishu Sink supports multiple chats and more message types.

- connectors/sink-feishu/README.md
- connectors/sink-feishu/config.yml.example
- connectors/sink-feishu/internal/bot.go
- connectors/sink-feishu/internal/server.go
- connectors/sink-feishu/sink-feishu.yml
**Changes:**
-  feishu sink support dynamic webhooks
> feat: feishu sink support dynamic webhooks

- connectors/sink-doris/README.md
- connectors/sink-doris/sink-doris.yaml
- connectors/sink-elasticsearch/README.md
- connectors/sink-elasticsearch/sink-es.yaml
- connectors/sink-k8s/README.md
- connectors/sink-k8s/sink-k8s.yml
- connectors/source-alicloud-billing/README.md
- connectors/source-alicloud-billing/source-alicloud-billing.yaml
- connectors/source-aws-billing/README.md
- connectors/source-aws-billing/source-aws-billing.yaml
> feat:modify image

- connectors/sink-aws-s3/README.md
- connectors/sink-display/README.md
- connectors/sink-doris/README.md
- connectors/sink-elasticsearch/README.md
- connectors/sink-email/README.md
- connectors/sink-feishu/README.md
- connectors/sink-http/README.md
- connectors/sink-k8s/README.md
- connectors/sink-mongodb/README.md
- connectors/sink-mysql/README.md
- connectors/sink-slack/README.md
- connectors/sink-tencentcloud-scf/README.md
- connectors/source-alicloud-billing/README.md
- connectors/source-aws-billing/README.md
- connectors/source-aws-s3/README.md
- connectors/source-aws-sns/README.md
- connectors/source-aws-sqs/README.md
- connectors/source-github/README.md
- connectors/source-http/README.md
- connectors/source-kafka/README.md
- connectors/source-mongodb/README.md
- connectors/source-mysql/README.md
- connectors/source-postgres/README.md
- connectors/source-tencentcloud-cos/README.md
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
**Changes:**
-
> docs: add titles and fix links

- connectors/sink-email/README.md
**Changes:**
- update image source
> docs: update image source

- connectors/sink-slack/README.md
Signed-off-by: mendesbarreto mendes-barreto@live.com
This PR closes #135
**Changes:**
> docs: Add raw query param to resource image from README

- connectors/sink-tencentcloud-scf/README.md
**Changes:**
- update connector doc (README)"connectors/sink-tencentcloud-scf"
> update connector doc "connectors/sink-tencentcloud-scf"

- connectors/sink-feishu/README.md
Singed-off-by: Emmanuel <nwokoloebuka84@gmail.com>
**Changes:**
- Changed 3 image URL in the /[vanus-connect](https://github.com/linkall-labs/vanus-connect)/[connectors](https://github.com/linkall-labs/vanus-connect/tree/main/connectors)/[sink-feishu](https://github.com/linkall-labs/vanus-connect/tree/main/connectors/sink-feishu)/README.md
> Docs[README]: Changed 3 images in README.md file

- connectors/sink-mongodb/internal/server.go
Signed-off-by: wenfeng <sxian.wang@gmail.com>
**Changes:**
- add bulk_size and upsert to mongodb sink
> feat: add bulk_size and upsert to mongodb sink

- connectors/sink-aws-s3/README.md
- connectors/sink-mysql/README.md
- connectors/source-aws-sqs/README.md
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
**Changes:**
- Updated docs temporarily until we standardized them to the new template
> docs: temporary updates connector md with old content

- connectors/sink-aws-s3/README.md
- connectors/sink-mysql/README.md
- connectors/source-aws-sqs/README.md
- connectors/source-tencentcloud-cos/README.md
**Changes:**
- Fixing the error cause on docusaurus
> docs: removed broken tag

- connectors/sink-aws-s3/README.md
- connectors/sink-mysql/README.md
- connectors/source-aws-sqs/README.md
- connectors/source-tencentcloud-cos/README.md
> docs: Removed error

- connectors/source-http/README.md
PR Summary
Update content/connectors/source/source-http for readability, without changing the content.
PR Type
[x]    Fix typos or format(punctuation, space, indentation, code block, etc.)
Signed-off-by: Matthew-Mu <matty.mu96@gmail.com>
> Style: Improve grammar within source-http 

- Makefile
- build/go/push-image.sh
- build/java/push-image.sh
Signed-off-by: wenfeng <sxian.wang@gmail.com>
**Changes:**
-
> build: add scripts to build all images with one click

- connectors/Templates/README.md
- connectors/Templates/sink.md
- connectors/Templates/source.md
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
> docs: add template documents for connectors

- connectors/Templates/sink.md
- connectors/Templates/source.md
**Changes:**
- update connector template
> docs: update connector template

- build/go/Dockerfile
- build/java/Dockerfile
- connectors/source-aws-billing/README.md
- connectors/source-aws-billing/internal/aws_billing.go
- connectors/source-aws-billing/internal/model.go
- connectors/source-aws-billing/source-aws-billing.yaml
> feat: modify aws billing source

- connectors/source-aws-billing/README.md
**Changes:**
- Reviewed documentation content and grammar
- tested the connector. Worked!
> docs: review and update of Amazon billing

- connectors/Templates/source.md
- connectors/source-aws-billing/README.md
- connectors/source-github/Dockerfile
- connectors/source-github/README.md
- connectors/source-github/pom.xml
- connectors/source-github/source-github.yaml
- connectors/source-github/src/main/java/com/linkall/source/github/Entrance.java
- connectors/source-github/src/main/java/com/linkall/source/github/GitHubConfig.java
- connectors/source-github/src/main/java/com/linkall/source/github/GitHubHttpAdapter.java
- connectors/source-github/src/main/java/com/linkall/source/github/GitHubHttpSource.java
- connectors/source-github/src/main/java/com/linkall/source/github/SecretConfig.java
- connectors/source-github/src/main/resources/config.json
- connectors/source-github/src/main/resources/secret.json
> refactor: modify source github code

- connectors/Templates/sink.md
- connectors/sink-slack/README.md
- connectors/sink-slack/sink-slack.yml
> feat: modify slack sink

- connectors/source-alicloud-billing/README.md
- connectors/source-alicloud-billing/internal/alicloud_billing.go
- connectors/source-alicloud-billing/source-alicloud-billing.yaml
- connectors/source-aws-billing/README.md
> feat: modify alicloud billing source

- connectors/source-alicloud-billing/README.md
- connectors/source-alicloud-billing/internal/alicloud_billing.go
- connectors/source-alicloud-billing/source-alicloud-billing.yaml
- connectors/source-aws-billing/README.md
- connectors/source-github/README.md
> feat: modify alibaba cloud biling source

- build/go/Dockerfile
- build/java/Dockerfile
> build: modify build file

- build/go/Dockerfile
- build/java/Dockerfile
- connectors/sink-doris/README.md
- connectors/sink-elasticsearch/README.md
- connectors/source-http/README.md
> docs: modify doc

- connectors/sink-email/README.md
> docs: modify email doc

- connectors/sink-slack/README.md
Reviewed and tested
**Changes:**
- Reviewed and tested.
> docs: review

- connectors/source-aws-s3/README.md
- connectors/source-aws-s3/pom.xml
- connectors/source-aws-s3/source-aws-s3.yaml
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/s3/Entrance.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/s3/S3Adapter.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/s3/S3Config.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/s3/S3Source.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/s3/SecretConfig.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/utils/AwsHelper.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/utils/FileUtil.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/utils/S3Util.java
- connectors/source-aws-s3/src/main/java/com/linkall/source/aws/utils/SQSUtil.java
- connectors/source-aws-s3/src/main/resources/config.json
- connectors/source-aws-s3/src/main/resources/secret.json
> refactor: refactor source aws s3

- connectors/source-aws-s3/Dockerfile
- connectors/source-aws-s3/pom.xml
- connectors/source-aws-sns/Dockerfile
- connectors/source-aws-sns/README.md
- connectors/source-aws-sns/pom.xml
- connectors/source-aws-sns/source-aws-sns.yaml
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/sns/Entrance.java
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/sns/SecretConfig.java
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/sns/SnsAdapter.java
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/sns/SnsConfig.java
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/sns/SnsSource.java
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/utils/AwsHelper.java
- connectors/source-aws-sns/src/main/java/com/linkall/source/aws/utils/SNSUtil.java
- connectors/source-aws-sns/src/main/resources/config.json
- connectors/source-aws-sns/src/main/resources/secret.json
- connectors/source-github/README.md
> refactor: refactor source sns

- connectors/source-aws-s3/README.md
- connectors/source-aws-s3/pom.xml
- connectors/source-aws-sns/README.md
- connectors/source-aws-sns/pom.xml
- connectors/source-aws-sqs/Dockerfile
- connectors/source-aws-sqs/README.md
- connectors/source-aws-sqs/pom.xml
- connectors/source-aws-sqs/source-aws-sqs.yaml
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/sqs/Entrance.java
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/sqs/SecretConfig.java
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/sqs/SqsAdapter.java
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/sqs/SqsConfig.java
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/sqs/SqsSource.java
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/utils/AwsHelper.java
- connectors/source-aws-sqs/src/main/java/com/linkall/source/aws/utils/SQSUtil.java
- connectors/source-aws-sqs/src/main/resources/config.json
- connectors/source-aws-sqs/src/main/resources/secret.json
> refacotr: refactor source aws sqs

- connectors/sink-email/README.md
- connectors/sink-feishu/README.md
- connectors/sink-slack/README.md
**Changes:**
- Change template <name>
> docs: Fix typos

- connectors/sink-feishu/README.md
Signed-off-by: Michaelg22 <mike.giroux22@outlook.com>
**Changes:**
-
> docs: fix typo

- connectors/source-github/pom.xml
- connectors/source-github/src/main/java/com/linkall/source/github/GitHubHttpSource.java
- connectors/source-kafka/Dockerfile
- connectors/source-kafka/README.md
- connectors/source-kafka/pom.xml
- connectors/source-kafka/source-kafka.yaml
- connectors/source-kafka/src/main/java/com/linkall/source/kafka/Entrance.java
- connectors/source-kafka/src/main/java/com/linkall/source/kafka/KafkaAdapter.java
- connectors/source-kafka/src/main/java/com/linkall/source/kafka/KafkaConfig.java
- connectors/source-kafka/src/main/java/com/linkall/source/kafka/KafkaSource.java
- connectors/source-kafka/src/main/java/com/linkall/source/kafka/KafkaWorker.java
- connectors/source-kafka/src/main/resources/config.json
> refactor: source kafka

- connectors/source-http/README.md
> docs: reviewed and tested

- connectors/source-aws-billing/README.md
> docs: Update billing

- connectors/sink-slack/README.md
> docs: update picture links

- connectors/source-aws-sns/README.md
**Changes:**
- reviewed and tested
> docs: AWS SNS reviewed

- connectors/source-aws-sqs/README.md
> docs: SQS reviewed

- connectors/sink-aws-s3/README.md
> docs: s3 sink updated tested

- connectors/sink-k8s/README.md
- connectors/sink-k8s/sink-k8s.yml
> docs: sink k8s readme

- connectors/sink-mysql/README.md
> docs: sink mysql readme

- templates/docs/README-sink.md
- templates/docs/README-source.md
- templates/docs/README.md
- templates/sink-go/README.md
- templates/sink-java/README.md
- templates/source-go/README.md
- templates/source-java/README.md
> doc: add template doc readme

- connectors/sink-display/README.md
**Changes:**
- Reviewed and tested
> docs: Display sink Reviewed and tested

- connectors/sink-http/README.md
> docs: http sink Reviewed and tested

- connectors/sink-email/README.md
- connectors/sink-email/internal/server.go
> feat: modify sink email

- connectors/sink-mysql/README.md
**Changes:**
- docs: Mysql sink reviewed and tested
> docs: Mysql sink reviewed and tested

- connectors/source-alicloud-billing/README.md
**Changes:**
- docs: Alibaba billing reviewed and test
> docs: Alibaba billing reviewed and test

- connectors/source-alicloud-billing/internal/alicloud_billing.go
> feat: modify alicloud billing source name

- connectors/sink-email/README.md
- connectors/sink-email/internal/server.go
- connectors/sink-email/sink-email.yml
- connectors/sink-slack/README.md
- connectors/sink-slack/internal/server.go
> Sink email

- connectors/sink-feishu/README.md
> docs: Feishu updated and tested

- connectors/sink-slack/README.md
> feat: modify sink slack

- connectors/sink-aws-s3/README.md
- connectors/sink-aws-s3/sink-aws-s3.yaml
- connectors/source-alicloud-billing/README.md
- connectors/source-alicloud-billing/source-alicloud-billing.yaml
- connectors/source-aws-billing/README.md
- connectors/source-aws-billing/source-aws-billing.yaml
- connectors/source-aws-s3/README.md
- connectors/source-aws-s3/source-aws-s3.yaml
- connectors/source-aws-sns/README.md
- connectors/source-aws-sns/source-aws-sns.yaml
- connectors/source-aws-sqs/README.md
- connectors/source-aws-sqs/source-aws-sqs.yaml
- connectors/source-github/README.md
- connectors/source-github/source-github.yaml
- proposals/sink_proposal_example.md
- proposals/source_proposal_example.md
**Changes:**
- add Proposal template
> Proposal template

- connectors/sink-snowflake/README.md
> feat: add sink snowflake

- connectors/sink-aws-s3/README.md
- connectors/sink-display/README.md
- connectors/sink-doris/README.md
- connectors/sink-elasticsearch/README.md
- connectors/sink-email/README.md
- connectors/sink-feishu/README.md
- connectors/sink-http/README.md
- connectors/sink-k8s/README.md
- connectors/sink-mongodb/README.md
- connectors/sink-mysql/README.md
- connectors/sink-slack/README.md
- connectors/sink-snowflake/README.md
- connectors/sink-tencentcloud-scf/README.md
- connectors/source-alicloud-billing/README.md
- connectors/source-aws-billing/README.md
- connectors/source-aws-s3/README.md
- connectors/source-aws-sns/README.md
- connectors/source-aws-sqs/README.md
- connectors/source-github/README.md
- connectors/source-http/README.md
- connectors/source-kafka/README.md
- connectors/source-mongodb/README.md
- connectors/source-mysql/README.md
- connectors/source-postgres/README.md
> feat: change vanus connnect address

- connectors/sink-google-sheets/README.md
- connectors/sink-google-sheets/internal/config.go
- connectors/sink-google-sheets/internal/service.go
- connectors/sink-google-sheets/internal/sink.go
- connectors/sink-google-sheets/internal/summary.go
- connectors/sink-google-sheets/internal/util.go
- connectors/sink-google-sheets/sink-google-sheets.yaml
> feat: sink google sheet

- connectors/sink-google-sheets/internal/sink.go
- connectors/sink-google-sheets/internal/summary.go
> feat: modify google sheet sink

- connectors/sink-http/internal/server.go
- connectors/source-github/internal/handler.go
> feat: gitHub source

- proposals/source_proposal_example.md
> Update proposal example

- proposals/source_proposal_example.md
> Fix: proposal example for connector source

- connectors/sink-google-sheets/README.md
- connectors/sink-google-sheets/internal/service.go
- connectors/sink-google-sheets/internal/sink.go
- connectors/sink-google-sheets/internal/summary.go
> feat: modify google sheet

- connectors/sink-google-sheets/internal/config.go
- connectors/sink-google-sheets/internal/service.go
- connectors/sink-google-sheets/internal/sink.go
- connectors/sink-google-sheets/internal/summary.go
> feat: support multi summary

- connectors/sink-google-sheets/internal/config.go
> feat: add tenant manager ut

- connectors/sink-google-sheets/cmd/main.go
- connectors/sink-google-sheets/internal/summary.go
> feat: fix google sheets summary

- connectors/sink-google-sheets/internal/service.go
> feat: INSERT_ROWS

- connectors/sink-snowflake/pom.xml
> feat: upgrade HikariCP version to 5.0.1

- connectors/README.md
> docs: how to add a connector

- connectors/sink-snowflake/pom.xml
- connectors/sink-snowflake/src/main/java/com/linkall/sink/snowflake/SnowflakeDatabase.java
> feat:  snowflake sink connection timeout

- connectors/sink-aws-s3/README.md
- connectors/sink-aws-s3/sink-aws-s3.yaml
- connectors/sink-feishu/README.md
> docs: update doc

- connectors/source-alicloud-billing/README.md
- connectors/source-alicloud-billing/internal/alicloud_billing.go
- connectors/source-alicloud-billing/internal/config.go
- connectors/source-alicloud-billing/internal/model.go
- connectors/source-aws-billing/README.md
- connectors/source-aws-billing/internal/aws_billing.go
- connectors/source-aws-billing/internal/config.go
> feat: modify aws and alibaba billing source

- connectors/source-chatgpt/internal/source.go
> feat: add source chatgpt

- connectors/source-chatgpt/README.md
- connectors/source-chatgpt/internal/source.go
> feat: modify source chatgpt

- connectors/README.md
- connectors/sink-feishu/README.md
- connectors/sink-feishu/internal/bot.go
- connectors/sink-feishu/internal/server.go
- connectors/sink-feishu/sink-feishu.yml
> feat: modify

- connectors/sink-feishu/go.mod
- connectors/sink-feishu/go.sum
- connectors/source-facebook/internal/event.go
- connectors/source-facebook/internal/server.go
> feat: modify source facebook

- connectors/sink-http/internal/server.go
> feat: http sink add response log

- proposals/sink_Mail_chimp_proposal.md
**Changes:**
- Create `sink_Mail_chimp_proposal.md` in proposals/ directory.
> docs: add proposal for mail chimp sink conncetor

- proposals/sink_facebook_lead_ads_proposal.md
**Changes:**
- Create ```sink_facebook_lead_ads_proposal.md``` in ```proposals/``` directory.
> Add sink connector proposal for Facebook Lead Ads

- connectors/sink-google-sheets/internal/sink.go
- connectors/source-alicloud-billing/internal/alicloud_billing.go
- connectors/source-aws-billing/internal/aws_billing.go
> feat: google sheet add lock

- connectors/source-cloudevents/go.mod
- connectors/source-cloudevents/go.sum
> feat: upgrade cdk

- connectors/source-cloudevents/internal/source.go
- connectors/source-github/internal/sink.go
> feat: github source add default port

- connectors/source-chatai/internal/source.go
> feat: add source chatai

- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/Constants.java
- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/DbWriter.java
- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/MySQLSink.java
- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/TableMetadata.java
- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/TableWriter.java
> feat: modify mysql sink

- connectors/source-chatai/internal/source.go
> feat: modify source chatai

- .gitignore
- connectors/source-custom-python/Dockerfile
- connectors/source-custom-python/cmd.py
- connectors/source-custom-python/setup.py
- connectors/source-custom-python/vanus/connect/customsource/__init__.py
- connectors/source-custom-python/vanus/connect/customsource/__main__.py
- connectors/source-custom-python/vanus/connect/customsource/run.py
- connectors/source-custom-python/vanus/connect/customsource/source.py
- connectors/source-labeling/Dockerfile
- connectors/source-labeling/cmd.py
- connectors/source-labeling/handler.py
- connectors/source-labeling/setup.py
- connectors/source-labeling/vanus/connect/labelingsource/__init__.py
- connectors/source-labeling/vanus/connect/labelingsource/__main__.py
- connectors/source-labeling/vanus/connect/labelingsource/labeling.py
> feat: add labeling source

- connectors/source-custom-python/vanus/connect/customsource/source.py
> feat: source-custom-python serves all path

- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/DbWriter.java
- connectors/source-shopify-app/go.mod
- connectors/source-shopify-app/go.sum
- connectors/source-shopify-app/internal/event.go
- connectors/source-shopify-app/internal/metadata.go
- connectors/source-shopify-app/internal/source.go
> feat: modify shipify source

- connectors/source-schedule/README.md
- connectors/source-schedule/internal/source.go
> feat: add source schedule

- connectors/source-schedule/README.md
- connectors/source-schedule/internal/config.go
- connectors/source-schedule/internal/source.go
> Source schedule

- connectors/source-chatai/go.mod
- connectors/source-chatai/go.sum
- connectors/source-chatai/internal/auth/auth.go
- connectors/source-chatai/internal/auth/config.go
- connectors/source-chatai/internal/chatai.go
- connectors/source-chatai/internal/config.go
- connectors/source-chatai/internal/ernie_bot/ernie_bot.go
- connectors/source-chatai/internal/gpt/gpt.go
- connectors/source-chatai/internal/source.go
- connectors/source-http/internal/config.go
- connectors/source-http/internal/server.go
- connectors/source-schedule/README.md
- connectors/source-schedule/internal/config.go
- connectors/source-schedule/internal/source.go
- connectors/source-shopify-app/internal/config.go
- connectors/source-shopify/internal/server.go
> feat: modify source

- connectors/sink-feishu/internal/bot.go
> feat: modify sink feishu

- connectors/sink-google-sheets/internal/service.go
- connectors/source-chatai/chat/config.go
- connectors/source-chatgpt/internal/config.go
- connectors/source-shopify-app/internal/source.go
> feat: modify connector

- connectors/sink-cloudevent/pom.xml
- connectors/sink-cloudevent/src/main/java/com/linkall/sink/example/CloudEventSink.java
> feat: sink cloudevent

- connectors/source-custom-python/Dockerfile
- connectors/source-custom-python/setup.py
- connectors/source-custom-python/vanus/connect/customsource/__init__.py
- connectors/source-custom-python/vanus/connect/customsource/__main__.py
- connectors/source-custom-python/vanus/connect/customsource/run.py
- connectors/source-custom-python/vanus/connect/customsource/source.py
- connectors/source-labeling/Dockerfile
- connectors/source-labeling/setup.py
- connectors/source-labeling/vanus/connect/labelingsource/__init__.py
- connectors/source-labeling/vanus/connect/labelingsource/__main__.py
- connectors/source-labeling/vanus/connect/labelingsource/smart.py
> feat: smart labeling

- connectors/source-alicloud-billing/internal/alicloud_billing.go
> feat: fix alicloud billing

- connectors/source-github-api/README.md
- connectors/source-github-api/internal/config.go
- connectors/source-github-api/internal/source.go
> multiple organizations

- connectors/sink-whatsapp/internal/config.go
- connectors/sink-whatsapp/internal/sink.go
- connectors/source-whatsapp/internal/config.go
- connectors/source-whatsapp/internal/source.go
> feat: whatsapp custom db file name

- connectors/source-github-api/internal/pr.go
fix: update getting pr detail instead of getting pr info from list of prs
> fix: update getting pr detail instead of getting pr info from list of prs

- connectors/sink-whatsapp/internal/config.go
- connectors/sink-whatsapp/internal/sink.go
- connectors/source-whatsapp/internal/config.go
- connectors/source-whatsapp/internal/source.go
> feat: whatsapp filename

- connectors/source-wxwork/go.mod
- connectors/source-wxwork/go.sum
- connectors/source-wxwork/internal/source.go
> block dup req

- connectors/source-labeling/vanus/connect/labelingsource/smart.py
> Feat smart labeling

- connectors/source-whatsapp/internal/source.go
> feat: modify whatsapp

- build/go/Dockerfile
> build: modify go dockerfile

- connectors/sink-mongodb/internal/server.go
> fix: modify sink mongodb xvcoll

- connectors/sink-email/README.md
- connectors/sink-email/internal/email.go
- connectors/sink-email/internal/model.go
- connectors/sink-email/internal/server.go
- connectors/sink-gmail/internal/gmail.go
- connectors/sink-gmail/internal/model.go
- connectors/sink-gmail/internal/sink.go
> feat: modify sink email and gmail data schema from receiver to to

- connectors/source-mongodb/src/main/java/com/linkall/connector/source/mongodb/MongoDBConfig.java
> feat: mongodb source add ssl_enable config

- connectors/sink-mysql/src/main/java/com/linkall/sink/mysql/TableWriter.java
> feat: sink mysql lock

- connectors/sink-feishu/go.mod
- connectors/sink-feishu/go.sum
- connectors/sink-feishu/internal/bot.go
- connectors/sink-feishu/internal/server.go
> feat: modify sink feishu response code

- connectors/sink-slack/go.mod
- connectors/sink-slack/go.sum
- connectors/sink-slack/internal/server.go
> feat: slack sink add err log

- connectors/source-http/internal/server.go
> feat: source http modify body is json check

- connectors/source-shopify-app/internal/config.go
- connectors/source-shopify-app/internal/source.go
> feat: source shopify app add delay second config

- connectors/sink-mandrill/README.md
> feat: add sink mandrill readme
